name: .NET Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    -
      run: dotnet build BucStop
